# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Code"
description: The thought of machine...

email: clementtph.com
#blog logo
logo: "/assets/images/ct_logo.jpg"
# blog cover
cover: "/assets/images/desk.jpg"

name: 'Clement Tan'
author: 'Clement Tan'
# author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://clementpeihengtan.github.io/clement-tph" # the base hostname & protocol for your site
baseurl: "/clement-tph"

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/TPHClement
    desc: Follow me on twitter
    # share_url: http://twitter.com/share
    # share_title: ?text=
    # share_link: "&amp;url="

  - icon:	facebook
    url:	https://www.facebook.com/tan.clement.52
    desc: Connect with me facebook
    # share_url: https://www.facebook.com/sharer.php
    # share_title: ?t=
    # share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/clementpeihengtan
    desc:	Fork me on github
    # share_url:
    # share_title:
    # share_link:

  - icon:	instagram
    url:	https://www.instagram.com/tan_clement/
    desc:	Follow me on instagram
    # share_url:
    # share_title:
    # share_link:

  - icon: linkedin
    url: https://www.linkedin.com/in/clement-pei-heng-tan-b84889105
    desc: Add me on linkedin
    # share_url:
    # share_title:
    # share_link:
